### ISSUE TITLE
Create a Storyboard Visualization for Website Presence

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#118]
### Overview
We need to do a content/journey mockup to communicate our intended user experience flow on the Hack for LA website. The interactions between the below information will need to be mapped out and communicated to the HfLA website team.

### Action Items
- [ ] Establish Figma mockup contents
   - [ ] Role Categories
   - [ ] Role Titles within Categories
   - [ ] Role Descriptions (from Markdown files)
- [ ] Establish content interactions with additional webpages/links
   - [ ] Community of Practice webpage
   - [ ] Community of Practice Slack Channels
   - [ ] Community of Practice Project Boards
   - [ ] Specific HfLA Project role descriptions
- [ ] Create Figma or Sketch user flow diagram
- [ ] Review diagram with UX/UI designers
   - [ ] Confirm that design direction aligns holistically with HfLA website user flow
- [ ] Get feedback and ask Design team to provide a few options for review in next meeting
- [ ] Finalize direction
   
### Resources/Instructions
[UX/UI CoP GitHub board](https://github.com/hackforla/UI-UX/projects/2)
[Role Markdown files](https://github.com/hackforla/civic-opportunity/tree/master/roles-1)
[Website Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=5326%3A26395)

**Comment by rfambro2** [comment]
![image](https://user-images.githubusercontent.com/67340971/105640379-b3fa1000-5e4b-11eb-95ca-803cba4fd29d.png)

Example Sketch for Storyboard

**Comment by rfambro2** [comment]
@dan This requires interaction with the HfLA website team.

**Comment by daniellex0** [comment]
Hi Ray, got it- how would you guys like to collaborate? Should we join the 9am meeting tomorrow?

**Comment by rfambro2** [comment]
@daniellex0 - Hey Danielle! No need to join tomorrow’s meeting. I think we still some things to talk through before we can bring you back in. Will keep you posted!

**Comment by daniellex0** [comment]
@rfambro2 Got it, sounds good!

**Comment by Arjayellis** [comment]
Onboarding slide deck - https://docs.google.com/presentation/u/1/d/127UC7q5JOgc5oPev4bbEdydchany-rVBkPRn4w6DMek/edit#slide=id.p

Figma - https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205

**Comment by patrickm-tan** [comment]
Got in touch with Danielle - lots of great information in terms of onboarding and HflA user flow

To-Do

- [ ] Revise and refine current action items to reflect "The Journey Map"
- [ ] Read and review previous onboarding research provided by ui-ux onboarding

**Comment by Arjayellis** [comment]
@patrickm-tan how are you doing on this issue? I would like to start speaking to users in order to further refine our project goals and initiatives, but would like to be able to clearly reference each step in the user journey during the process so we can identify the gaps.

**Comment by patrickm-tan** [comment]
**Journey Map Action Items**

- [ ] Establish the stages of a volunteer's journey
- [ ] Establish key moments in a volunteer's journey
- [ ] Establish the thoughts/feelings of the volunteer at the given stage
- [ ] Establish painpoints
- [ ] Establish key touchpoints
- [ ] Establish potential opportunities at each stage

**To-Do**

- [x]  Revise and refine current action items to reflect "The Journey Map"
- [x]  Read and review previous onboarding research provided by ui-ux onboarding

**Research Needs**
- [ ] New volunteers and their experience finding HfLA (and first few weeks)
- [ ] Past volunteers and their experience after HfLA

**Comment by patrickm-tan** [comment]
Link to miro board:
https://miro.com/app/board/o9J_lFFy7Gk=/

**Comment by Arjayellis** [comment]
Draft for user interview questions. Let's review both sets and finalize a list later this week. https://docs.google.com/document/d/1pX829XB2s4IwNNw7AnhJggfgRaerBTAQz_8L0ZqaSKA/edit

@patrickm-tan @alexilee

**Comment by patrickm-tan** [comment]
Sounds good - will review the doc and also add some questions I brainstormed over the week. Then later reconvene to review the doc and move on with interviews

**Comment by patrickm-tan** [comment]
https://miro.com/welcomeonboard/SDlUYnZBdDJLdUJJbk9kcHA2MnZ5R0RvdDlIclZOdm1sUndBa0p0Y1BudkxxOWpyQ0J0Mmp5S1FKNG9wQkF3UnwzMDc0NDU3MzU2NTM1MzM1ODMx

@Jackie-UX you can access the journey map with this link, feel free to add any comments/experiences you had as a volunteer

**Comment by patrickm-tan** [comment]
Took a look at https://docs.google.com/document/d/1pX829XB2s4IwNNw7AnhJggfgRaerBTAQz_8L0ZqaSKA/edit

Questions look good to me, I only need really one thing in regard to the journey map and that would be just the overall experience at each "stage" of their journey, so if we can look to ask that at each stage. Other than that I should be able to put a lot of the info into the journey map.

Just eyeballing a number but I can see it being roughly 7 minutes a stage x 5 for asking and answering the questions. The heavier answers are the middle stages like Onboarding and Contribution, but I think it could even out with the easier questions throughout the interview. So roughly looking at 35 minutes of interviews give or take? Thoughts?

**Comment by patrickm-tan** [comment]
Getting more insight with [issue 152](https://github.com/hackforla/civic-opportunity/issues/152), will update the map accordingly
