### ISSUE TITLE
Instructions cards in Open Roles repos - Process Documentation

### ISSUE THREAD

**Issue by rjdoria** [hackforla/civic-opportunity#123]
### Overview
For the Open Roles boards under each CoP, update the 'Start Here' and 'opportunity' cards under the Instructions column.

### Action Items
- [x] Pilot updated changes with one repo first (Marketing) and review before proceeding to the rest.
  - [x] 'Start Here' card
  - [x] 'Find a volunteer opportunity' card
  - [x] 'Post a volunteer opportunity' card
  - [x] 'Remove a volunteer opportunity' card
  - [x] Locate 'Recruiting Pipelines' form and spreadsheet
  - [x] Update volunteer card links in 'Start Here' card
  - [x] Update document links in 'Start Here' card

Gather all 'Recruiting Pipelines' documents and messaging in one place
- [x] Create new Issue and link in Resources

Repeat steps for CoPs with open roles:
- [x] Data Science

Data Science:
- [x] Update Open Roles Board
- [x] Create Pipeline documents
- [x] Update document links in 'Start Here' card

### Resources/Instructions
Check [open roles](https://github.com/hackforla/communities-of-practice) 
[Issue #124](https://github.com/hackforla/civic-opportunity/issues/124)

**Comment by rjdoria** [comment]
@Olivia-Chiong 
I cannot edit cards for the following repos:
  - UI/UX Design
  - UI/UX Research
  - Development
  - Ops
  - PM
  - Fundraising

 I need permission for at least the UI/UX one to grab the card text and work on Marketing, Data Science.

**Comment by Olivia-Chiong** [comment]
@rjdoria I just added you to the UI/UX repo.

**Comment by Olivia-Chiong** [comment]
@rjdoria also added you to ops, dev, marketing and fundraising

**Comment by rjdoria** [comment]
Created Pipeline documents for Data Science and updated links in the Open Roles board

**Comment by rfambro2** [comment]
@rjdoria We have a homepage for all role boards now. All new boards will be added here in the future - https://github.com/hackforla/communities-of-practice:

'Start Here' card
 'Find a volunteer opportunity' card
 'Post a volunteer opportunity' card
 'Remove a volunteer opportunity' card
 Locate 'Recruiting Pipelines' form and spreadsheet
 Update volunteer card links in 'Start Here' card
 Update document links in 'Start Here' card


CoP boards that need the above information added:

- [ ] https://github.com/hackforla/development/projects/2
- [ ] https://github.com/hackforla/ops/projects/1
- [ ] https://github.com/hackforla/product-management/projects/8

**Comment by rjdoria** [comment]
Updated 'Start Here' cards for the 3 CoP boards
Just need to update Pipeline links for the Ops board

**Comment by patrickm-tan** [comment]
No longer relevant
