### ISSUE TITLE
Recruiting Pipelines documents and messaging

### ISSUE THREAD

**Issue by rjdoria** [hackforla/civic-opportunity#124]
### Overview
Gather all 'Recruiting Pipelines' documents and messaging in one place
Create missing 'Recruiting Pipeline' documents
Document process for creating new docs in Guide

### Action Items
Identify the following three documents for each CoP:
- 'Recruiting Pipelines' google form
- 'Recruiting Pipelines' response spreadsheet
- ~Messaging document or examples of messaging in Slack~

(Pipeline documents need to be revised or created)

Progress:
- [x] Make guide for creating 'Recruiting Pipeline' form and response sheet
- [ ] Pilot guide with another team member
- [x] Ensure 'Recruiting Pipeline' form and response sheet created for each CoP

Link to documents in Resources for the each CoP:
- [ ] UI/UX
- [x] Data Science
- [x] Development (programming)
- [x] Ops
- [x] Product Management
- [ ] Marketing
- [x] Fundraising

### Resources/Instructions
[Guide: Create Recruitment Pipeline Form and Response Sheet](https://docs.google.com/document/d/1C4py2RaRYwLLrAy7kaVqwY9Q9kbjq3_7KeMGjZmgDxQ/edit)
UI/UX - [Pipelines form](https://docs.google.com/forms/d/e/1FAIpQLSfB7lBSeYMhN8EBS46qdAVnd7N5Ocx5lPEwEvu9Gfl7bLbACA/viewform),  [Pipelines response sheet](https://docs.google.com/spreadsheets/d/1TuDelZ_pCg1pc9murZaYMsnv7CgEwXvoVtH5Jkt32XM/preview), Messaging
Data Science - [Pipelines form](https://docs.google.com/forms/d/e/1FAIpQLSf7jz_Uj7Luxrlv7ObR2HFEHMDnTfwaFcXR1LYlcwbz-Pz4cw/viewform), [Pipelines response sheet](https://docs.google.com/spreadsheets/d/1yFCDM50HiaOICZWWQI4vT3TXrqd_QRMm2uEboN38iQs/preview), Messaging
Development - [Pipelines form](https://docs.google.com/forms/d/1Uph68eajHxfSAtbKIuQko5Z_73mMUnL0XUea701l1V0/viewform), [Pipelines response sheet](https://docs.google.com/spreadsheets/d/1Qv2jbtwkUDXvmBl1DcIp-jH_hAd6P2FRiHlQLQjHIT4/preview), Messaging
Ops - [Pipelines form](https://docs.google.com/forms/d/e/1FAIpQLSdJFYAa6mt2hA4NskFL85_p00ZHT8ThIECdO1wpyFGx0Xp3DA/viewform), [Pipelines response sheet](https://docs.google.com/spreadsheets/d/1sPu4ylVz20SHYSezoo_DDO_gh1ifv0VE2QlCoFwRaRA/preview), Messaging
Product - [Pipelines form](https://docs.google.com/forms/d/1S8MycNqOkaothsgArzOnPh2iYUQyfEa4w7ZQhia2otA/viewform), [Pipelines response sheet](https://docs.google.com/spreadsheets/d/1WFiWycdt_i3Oi11YFld5k-IBMpnOmJmdmOaZvLIvBsk/preview), Messaging
Marketing - [Pipelines form](https://docs.google.com/forms/d/e/1FAIpQLScDrgJHndp48GUbbpj4mlkbqYM0nuaU0Rr6WojKCXM9k9iNNA/viewform), [Pipelines response sheet](https://docs.google.com/spreadsheets/d/19VBho1i-3kmteCUy-T0SsMu2NdblOblI_s2cVRxdC8U/preview), [Messaging](https://docs.google.com/document/d/1QM8FfScmqUixykckXmB2qG5Y3jY6Tpp_2dDXt8Ez4gA/edit)
Fundraising - [Pipelines form](https://docs.google.com/forms/d/10Y_e1Zmt_PqoDk9P2NCnbGmKOfS2t0m4sETg_lthh2k/viewform), [Pipelines response sheet](https://docs.google.com/spreadsheets/d/1Q1YyP_8sSBFBSfzEN66MS6TvJ6PR2HtmpnhfCk7sKpE/preview), Messaging

**Comment by rjdoria** [comment]
@ExperimentsInHonesty 
In testing the guide, I found out that the test responses do not keep the formatting set in the Response Sheet (align and text wrapping).

Should I keep these in the guide as later steps somehow or forgo them entirely?
(I will proceed forward with an alternate version of the guide just to keep things moving forward)

**Comment by rjdoria** [comment]
@tan-zhou Would you mind piloting the Guide for me? I included it in the Resources. The Practice Area to create would be Ops.

Also, could you take a look at the UX Pipeline Response Sheet? There are three channels we can add into the main response sheet. Thanks!

**Comment by tan-zhou** [comment]
I'll take this issue to Thad and ask his advice on how we should formulate the Google sheet. Will come back and update the issue with his answers

**Comment by rjdoria** [comment]
Obstacles
- New responses on Response tab still insert a new line; even if formulas on Display Sheet are properly set up on creation they will fail to read new responses unless formulas are updated
- Even after deleting test responses, new responses are inserted on a lower row which may create gaps on the Display Sheet

Questions:
How to create solution to automatically update formulas?
Any other solutions regarding connectivity between Form and Response Sheet that eliminates this issue?

**Comment by tan-zhou** [comment]
After the current Google sheet behavior issue has been solved, we should add column to pipeline spreadsheet for length of joining process e.g. how long does it take from requesting to join to being proved in the group?

**Comment by rjdoria** [comment]
Using Zapier to create issue to validate new Pipeline response:
- Signed up to Zapier using Civic Opp gmail
- Connect to Google Sheets using civicopportunity@hackforla.org
  - [ ] civicopportunity@hackforla.org needs access to documents in Google Drive

**Comment by rjdoria** [comment]
Next steps:
-[ ] Give civicopportunityproject@gmail.com access to Google Drive
-[ ] Create zap for Marketing Pipeline response sheet
-[ ] Pilot creation of Issue from zap trigger
-[ ] Revise Pipeline docs for new Zapier process
-[ ] Create zaps for other Pipeline docs

**Comment by Civic-Opportunity-Project** [comment]
- [ ] Need to authorize Zapier connection to Hack for LA organization in GitHub

**Comment by rjdoria** [comment]
Zapier pilot with Marketing repo: [Issue #38](https://github.com/hackforla/marketing/issues/38)

Progress: 
- Zapier connection to Marketing repo tested with success
- Zapier trigger (new row on Marketing Pipelines response sheet) failed
  - Marketing Pipelines already have responses, pilot with an empty response sheet instead

**Comment by rjdoria** [comment]
Pilot final updates with Fundraising Recruiting docs

Progress:
- Fundraising Pipeline response sheet revised with Display sheet and refreshed link with Form
- Updated Create Issue text with link to Response Sheet and channel details
- Test successful and document is now live, see [Issue #19](https://github.com/hackforla/revenue/issues/19)
- Links updated in Open Roles repo and this issue's resources

**Comment by rjdoria** [comment]
Blocker:
Need to add @Civic-Opportunity-Project to the following repos:
- Product Management
- Data Science
- Ops
- Engineering
- UI/UX (can wait until after existing responses are resolved)

**Comment by ExperimentsInHonesty** [comment]
@rjdoria are you asking to add a user to the GitHub repos?  I'm unclear what you are asking for

**Comment by rjdoria** [comment]
Progress:
Steps
- Unlink form and reconnect to fresh response sheet, rename as Responses
- Create new Zap and connect to pipeline doc
- Set up 'Create Issue' action with issue details, link to pipeline doc
- Test connection to set up, enter column hints as final test response
- Update Display column and Display Sheet formulas
- Update links in Issue #124 resources and Open Roles board

- [ ] Product [Issue #217](https://github.com/hackforla/product-management/issues/217)

**Comment by rjdoria** [comment]
Zapier test complete. Pipeline doc now live.

**Comment by rjdoria** [comment]
Progress:
Finished updating Engineering pipeline docs.

Next steps:
Finish up guide with Zapier steps.
Pilot guide and create Ops pipeline docs

**Comment by rjdoria** [comment]
Progress:
Created Ops pipeline docs

Concern:
Max 5 Zaps before upgrading Zapier plan

**Comment by ExperimentsInHonesty** [comment]
Hi @rjdoria,  I went to the pipeline link on ux community of practice and it took me to the pipleline page instead of the display page, because that pipeline page is not hidden yet, etc.  please make sure that the viewer only sees the display page

https://docs.google.com/spreadsheets/d/1TuDelZ_pCg1pc9murZaYMsnv7CgEwXvoVtH5Jkt32XM/edit#gid=34538959

**Comment by rjdoria** [comment]
No progress yet. I will pick back up next week.

Next steps:
Refresh link to Form and manually re-enter submitted responses for the following CoPs
- [ ] Marketing
- [ ] UI/UX
Turn on Zapier automation
- [ ] Create new gmail
- [ ] Marketing Zap
- [ ] UI/UX Zap

**Comment by rjdoria** [comment]
Refreshed link to Form and manually re-submitted responses for Marketing and UI/UX.

Next steps:
- Update formatting for Display Sheet
- Turn on Zapier automation

**Comment by rjdoria** [comment]
Progress:
- Created civicopportunityproject2@gmail.com and saved login in 1Password
- Created Zapier and Github accounts
- Updated response sheet and created new Zaps for Marketing and UI/UX

**Comment by rjdoria** [comment]
Zapier tests completed
- [] Marketing [Issue #49](https://github.com/hackforla/marketing/issues/49)
- [] UI/UX

**Comment by alexilee** [comment]
Moving to 'Done' to clean up board.
