### ISSUE TITLE
Create First Dump of Ideas on Miro Board

### ISSUE THREAD

**Issue by alexilee** [hackforla/civic-opportunity#138]
### Overview
Brainstorm ideas to visually represent the addressable market for workforce development in LA. Then, have the team review for next steps. We want to answer questions like:
- What is the total number of unemployed people in LA?
- What is the number of unemployed people who have been in the tech industry?
- How many people are graduating from bootcamps in LA? How many people are graduating from CS programs? Design programs? etc.
- What is the total number of jobs available in LA?

### Action Items
- [x] Write down questions to answer on board
- [ ] Initial research to answer questions
- [ ] Create outline of user journey map
- [ ] Have team review for feedback

### Resources/Instructions
[Miro Board](https://miro.com/app/board/o9J_lUHfQZ8=/)

**Comment by patrickm-tan** [comment]
no longer relevant
