### ISSUE TITLE
Procedure write-up: Publicize open volunteer opportunities

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#141]
### Overview
We need a defined process for publicizing open volunteer opportunities so that we can fill roles in a timely way.

### Action Items
Add to and revise this list:
- [ ] Get roles posted to Role Boards
- [ ] Share new role with Community of Practice
- [ ] Ask Community of Practice to post the pipelines, opportunity and/or interest list (TBD)
- [ ] If enough roles in one area, hold a role specific onboarding

### Resources/Instructions
[Community of Practice Board](https://github.com/hackforla/communities-of-practice/blob/main/README.md)

**Comment by patrickm-tan** [comment]
No longer relevant
