### ISSUE TITLE
Collabathon

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#36]
### Overview
Bring on a Special Projects Coordinator to setup/coordinate Collabathon project deliverables.

### Action Items

- [ ] Attend Wednesday team meetings (12pm PDT)
- [ ] Provide HfLA updates to organizer committee
- [ ] Ensure that other Special Project team members execute and complete assigned deliverables related to Collabathon
- [ ] Identify Collabathon event dates
   - [ ] Add Collabathon event dates to Bonnie's calendar
   - [ ] Add Collabathon event dates to HfLA calendar
- [ ] Aid in recruitment of Collabathon Product Manager

### Resources/Instructions
[General Role Definitions](https://docs.google.com/document/d/1X6d6-Sm_QDQPobiRfqachCSajAOpqRLVUsdCnczhhts/edit#heading=h.9gdculnesmid)
[volunteer match](https://www.volunteermatch.org/)
[Marketing Role Definitions](https://docs.google.com/document/d/1SQvBa8ctXJO78_ryiY5ejIBE3V7PDfA5n9A66j-3Ars/edit)
