### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#37]
### Overview
Establish Project Templates.

### Action Items

- [ ] Identify appropriate templates to use for your project
- [ ] Work with Project Team to use each Template as a focus guideline
- [ ] Iterate on Templates as necessary while seeking input from Leadership

**Comment by ExperimentsInHonesty** [comment]
unsure what this was in relation to, so closing as unplanned
