### ISSUE TITLE
 Communities of Practice (UX and Product)

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#46]
### Overview
Establish necessary Communities of Practice for various project roles.

### Action Items

- [x] Identify volunteers in UX and Product roles
- [x] Compile volunteers into CoP Slack group
- [x] Send out survey to Slack group to gauge availability and interest
- [x] Use common availability to establish meeting cadence
- [x] Host weekly (or bi-weekly) CoP

### Resources/Instructions
[Product Management Community of Practice - Survey Responses](https://docs.google.com/forms/d/1oop91HNNGa2g_K5M1uZ9gqo4utP0FMNhaOrWObioB9o/edit#responses)
[UX/UI Community of Practice - Survey Responses](https://docs.google.com/forms/d/1KESG6QEuwz7thGAtd02vlEVZh95Vc864QAH74qkT_v8/edit#responses)
