### ISSUE TITLE
Identifying Process for Filling Open Roles Internally

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#5]
### Overview
Create and test a manual process prior to digital product development.

### Action Items
- [ ] PM
   - [ ] Model as-is process
   - [ ] Validate process
   - [ ] Create proposal for internal process to get needs from PMs in a way that is scalable and transparent
   - [ ] Review the proposal with Bonnie
   - [ ] Engage UX team member
- [ ] UX / PM
    - [ ] Review with PMs after sign-off
    - [ ] Revise
    - [ ] Test with a single PM/project
    - [ ] Revise
    - [ ] Test with multiple PMs

### Resources
[Project Recruiting Needs](https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
#all-project-leads
https://hackforla.slack.com/archives/C010LNXH2JY

**Comment by rfambro2** [comment]
@ExperimentsInHonesty @abi-a - I took a stab at putting our process flow into a graphic sequence of events. Let's discuss this morning.

**Comment by rfambro2** [comment]
This issue was created very early on in the project and never really got hashed out due to focus on other areas. I think we may be past the point of mapping out the old process and can now be intentional about tracking the new processes that we've created. Every team member should be diligent about documenting all critical steps throughout the journey of the project. We should create a new Product Development Flowchart.

**Comment by patrickm-tan** [comment]
No longer relevant
