### ISSUE TITLE
Add all Milestones to Milestone Card

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#60]
### Overview
We need to be able to see milestones on the project board for easier navigation.

### Action Items

- [x] Create Milestone Project Card
- [x] Search each milestone finding it's URL
- [x] Add to card

### Resources/Instructions
[Milestone Card](https://github.com/hackforla/civic-opportunity/projects/1#card-44302907)
