### ISSUE TITLE
Create/Refine Personas

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#7]
### Overview
We need to build personas to confirm ongoing path forward.

### Action Items

- [ ] Interview PMs to gather information necessary for persona creation focusing on requirement to fill open roles
- [ ] Evaluate other team members responsibilities in the role identification and specific needs (e.g. tech lead)
- [ ] Create additional personas if necessary
- [ ] Release dependency on Issue #6 

### Resources/Instructions
See Bonnie or Abi for introductions to other PMs

**Comment by patrickm-tan** [comment]
No longer relevant
