### ISSUE TITLE
Engineering Community of Practice Creation

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#70]
### Overview
We would like to gauge the HfLA interest level for the creation of an Engineering Community of Practice.

### Action Items

- [ ] Review 1st Version Survey
- [ ] Incorporate Comments/Feedback
- [ ] Finalize Survey
- [ ] Send Survey Out to Engineering Group
- [ ] Create Google Doc Directory of HfLA Engineers

### Resources/Instructions
Use UX/UI and Product Management Survey Templates to create survey

**Comment by patrickm-tan** [comment]
Engineering CoP exists
