### ISSUE TITLE
Establish HfLA Affinity Groups

### ISSUE THREAD

**Issue by rfambro2** [hackforla/civic-opportunity#73]
### Dependency
Jayashree's return 

### Overview
Being able to connect with peer groups through shared life experiences can be instrumental to professional confidence, growth and mentorship. HfLA should provide spaces for volunteers to connect with like-minded peers. 

### Action Items

- [ ] Create a Google Form Questionnaire to gauge participation interest Affinity Groups
- [ ] Review questions with HfLA executive leadership
- [ ] Finalize Form and send out to the network
- [ ] Create necessary Slack Groups and publicize (We probably don't need to create Communities of Practice for these, but rather just them exist as Slack support channels?)

Examples of potential affinity groups are: Veterans in Tech, Women in Tech, Parents in Tech, LGBTQ in Tech, Latinos in Tech, Black in Tech, etc.

### Resources/Instructions
[Draft Google Form Questions](https://docs.google.com/document/d/1fUcVXsA7Yw7gs79hMrPuMgL1LIqLoBgAxm7_HixP1Xg/edit)
[Draft Google Form](https://docs.google.com/forms/d/1aJz9sijWCIVQnz2dbuO5p18WTQltAJTAJqmwUSjecMg/edit)

**Comment by JC789** [comment]
Updated the Google Doc and created a survey. Provided the link.

**Comment by rfambro2** [comment]
@rfambro2 - Created an issue to create Civic Opportunity creation guide

**Comment by rfambro2** [comment]
@JC789 - In the interim before we have the Guide set up, you can reference some of the Google Form Templates here and use the same language setup.

https://drive.google.com/drive/folders/1Xs45jBcs6gTZazkxN00yLejzGFp26AkH

**Comment by JC789** [comment]
@rfambro2 Updated the Google Doc again and created a survey. Provided the link above.

**Comment by JC789** [comment]
Survey updated and including a write up for Slack post here:
Hi everyone, the Hack for LA civic-opportunity team would appreciate your help with gauging interest for Affinity Groups and gather feedback. Our objective is to spark interaction and support and create forums where needed. Please fill out this quick survey and add your input.

**Comment by JC789** [comment]
Updated Survey and write up for Slack post:
**Hi everyone, the Hack for LA civic-opportunity team would appreciate your help with gauging interest for our Affinity Groups. Our objective is to empower all volunteers with value by promoting an environment for inclusiveness. Please fill out this quick survey and add your input.**

**Comment by JC789** [comment]
Hi everyone, the Hack for LA civic-opportunity team would appreciate your help with gauging interest for our Affinity Groups. Our objective is to empower all volunteers by promoting an environment for inclusiveness. Please fill out this 1 minute survey.

**Comment by ExperimentsInHonesty** [comment]
This is what I ended up posting
Bonnie  5:54 PM
@channel, the Hack for LA #civic-opportunity team would like to know if you want HfLA Affinity Groups. Our objective is to empower all volunteers by promoting an environment for inclusiveness. Please fill out this 1 minute survey. https://forms.gle/9XRFQPJYVC8Mk3ja8

**Comment by ExperimentsInHonesty** [comment]
I posted again just now. 4:12pm

**Comment by JC789** [comment]
44 responses with new post

**Comment by tan-zhou** [comment]
Hi Jayashree, just want to share my thoughts on the issue. I think the survey results help us understand the issue better. 

1. I did some quick calculations 

- The average rating for "How likely are you to participate in the channels listed above (including Other) in Slack?" is 3.3, with 53% of responses rated 4, or 5. 
- Among the 26 responses that checked "Women in Tech", the average rating for "How likely are you to participate in the channels listed above (including Other) in Slack?" is 3.9, and 73% out of 26 responses rated 4 or 5. 

So in general, survey results showed that people have a neutral attitude towards participating in affinity channels. For those who checked "Women in Tech" in the first question, around 70% of them said they are more likely to participant in the channel. 

2.  In the Wiki Overview for Affinity Groups, we have **"Being able to connect peer groups through shared life experiences can be instrumental to professional confidence, growth and mentorship"**. The question that emerged from the survey results is: 

What specific action items/activities that these channels need to do to link "connect peer groups" with the objective - "professional confidence, growth, and mentorship". We want to know what needs to happen at these channels for them to able to help volunteers achieve the objective. 

I recommend against doing an open-ended survey asking what activities people what to see because essentially we are asking them to guess what they like, and it's hard to verify these guesses via a survey.

I recommend doing observations in similar groups, for example, women in tech groups, channels, and see what activities are happening there, collect evidence on participants behaviors, engagements.

**Comment by JC789** [comment]
Hi Tan,
Thanks for providing further feedback. I agree an open-ended survey asking for suggestions might not work the best. A more pointed question might be to ask what channels in Slack (across all the ones you are part of) are you most active/interested in/ find useful with suggestions such as jobs, articles, events.  

Observational data gathering would be beneficial, but it would require more than one person to gather that data, I think? Some Slack groups have so many channels that it might take some time to observe channels and see activity. It would be easier to reach out to the Slack channel organizer and ask for data regarding the most active channels like Bonnie would provide for HLA. 

Another option is to reach out to individual contributors/leads in each HfLA group and ask f they would fill out a survey (sometimes more convenient for the participant). Or conduct interviews and ask what members are looking for or what are the expectations for participating in HfLA and are current expectations met with existing channels? Also, what channels do they truly find helpful and currently actively are participants? These questions would more directly help with the overview point 2.

**Comment by JC789** [comment]
Hi Tan,
Thanks for providing further feedback. I agree an open-ended survey asking for suggestions might not work the best. A more pointed question might be to ask what channels in Slack (across all the ones you are part of) are you most active/interested in/ find useful with suggestions such as jobs, articles, events.

Observational data gathering would be beneficial, but it would require more than one person to gather that data, I think? Some Slack groups have so many channels that it might take some time to observe channels and see activity. It would be easier to reach out to the Slack channel organizer and ask for data regarding the most active channels like Bonnie would provide for HLA.

Another option is to reach out to individual contributors/leads in each HfLA group and ask f they would fill out a survey (sometimes more convenient for the participant). Or conduct interviews and ask what members are looking for or what are the expectations for participating in HfLA and are current expectations met with existing channels? Also, what channels do they truly find helpful and currently actively are participants? These questions would more directly help with the overview point 2.

    On Sunday, April 11, 2021, 03:17:28 PM EDT, tan-zhou ***@***.***> wrote:  
 
 


Hi Jayashree, just want to share my thoughts on the issue. I think the survey results help us understand the issue better.
   
   - I did some quick calculations
   
   - The average rating for "How likely are you to participate in the channels listed above (including Other) in Slack?" is 3.3, with 53% of responses rated 4, or 5.
   - Among the 26 responses that checked "Women in Tech", the average rating for "How likely are you to participate in the channels listed above (including Other) in Slack?" is 3.9, and 73% out of 26 responses rated 4 or 5.

So in general, survey results showed that people have a neutral attitude towards participating in affinity channels. For those who checked "Women in Tech" in the first question, around 70% of them said they are more likely to participant in the channel.
   
   - In the Wiki Overview for Affinity Groups, we have "Being able to connect peer groups through shared life experiences can be instrumental to professional confidence, growth and mentorship". The question that emerged from the survey results is:

What specific action items/activities that these channels need to do to link "connect peer groups" with the objective - "professional confidence, growth, and mentorship". We want to know what needs to happen at these channels for them to able to help volunteers achieve the objective.

I recommend against doing an open-ended survey asking what activities people what to see because essentially we are asking them to guess what they like, and it's hard to verify these guesses via a survey.

I recommend doing observations in similar groups, for example, women in tech groups, channels, and see what activities are happening there, collect evidence on participants behaviors, engagements.

**Comment by JC789** [comment]
Potential questions for survey or interviews: (questions are also in the Draft Google Form Questions link above)
Update: 4/15/2021
Additional questions for direct 1:1 HfLA group members:
**What other Slack channels are you part of that you find most helpful?
How many Slack channels do you check regularly (in HfLA and others)?
Are you currently a regular (post a comment at least once a week) contributor to any Slack channels outside of HfLA?
Do you feel that HfLA has the right amount of channels in Slack currently?
If not why? 
Would you like to be a moderator for one of HfLA Slack channels? (Post relevant content regularly and make sure comments are relevant for the channel)**

**Comment by Arjayellis** [comment]
Bonnie will be asking each of the CoP leaders to monitor the job channels and repost appropriate links as well as try other types of posts to monitor outcomes.

**Comment by tan-zhou** [comment]
Suggested by Netflix expert: created an open-formed discussion instead of specific channels, and moderations.

**Comment by Arjayellis** [comment]
Just for clarification - the advice given to me was to create an open forum initially in order to get a discussion started. This would give people a chance to speak up about what they have seen work before or what they feel might be helpful for the organization. The outcome would ideally be a better idea of what practices we can implement, or individuals coming forward who would be willing to take ownership of one or more parts of the process. Due to the varying schedules of volunteers, we could host 2 or more sessions so everyone would have a chance to participate. Bonnie will be mulling it over before we make a decision.

**Comment by patrickm-tan** [comment]
We decided not to create these groups for now
