### ISSUE TITLE
Create Markdown file for each HfLA volunteer role

### ISSUE THREAD

**Issue by tan-zhou** [hackforla/civic-opportunity#99]
### Overview
We need to create individual markdown files for each of the hlfa roles so they are ready to display on the website.

### Action Items
Add the issue number and check off the box after a role is created

- [x] Product Manager #86 
- [x] Product Owner #88   
- [x] Business Analyst #89 
- [x] Marketing/Communications Coordinator #111 
- [x] Marketing/Communications Intern #110 
- [x] Marketing/Communications Manager #113 
- [x] Marketing/Communications Director #114 
- [x] UI Designer #102 
- [x] UX Designer #103 
- [x] UX Researcher #100 
- [x] Content Strategist/UX Writer #104
- [x] Data Scientist #90 
- [x] Data Analyst #91 
- [x] Database Architect #92  
- [x] Front-End Developer #105 
- [x] Back-End Developer #106 
- [x] Full-Stack Developer #107 
- [x] QA Engineer #108 
- [x] Data Engineer (DevOps) #109 
- [x] Special Projects Coordinator #115 

### Resources/Instructions
- Break down role description into Categories #62

**Comment by tan-zhou** [comment]
Bonnie needs to review the process by which we are committing roles to the repository.

**Comment by tan-zhou** [comment]
Copy and add the following list to "Action Items" in each role issue

- [x] Format the text in Markdown in the comment from the general description
- [x] Create a Markdown file in role-1 branch, under role-1 folder
- [x] Check the box this role in issue #99
